[package]
name = "wiremock_basics"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
serde_json = { workspace = true }
semver = "1.0.21"
thiserror = "1.0.56"
anyhow = "1.0.79"

[dev-dependencies]
googletest = { workspace = true }
tokio = { workspace = true }
wiremock = { workspace = true }
